Upgrade net.tnrd.nsubstitute v4.2.2 to v4.4.0
```
error CS0246: The type or namespace name 'NSubstitute' could not be found (are you missing a using directive or an assembly reference?)
```